development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  database: <%= ENV["DATABASE"] %>
  database_host: <%= ENV["DATABASE_HOST"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>